### ISSUE TITLE
repalce get_dummy with one_hot_encoder and save artifact

### ISSUE THREAD

**Issue by YotamAflalo** [YotamAflalo/MLOPS_mid_project#1]

**Comment by YotamAflalo** [comment]
make sure the transformer is saved  as pkl for consistency
here some example: 
https://stackoverflow.com/questions/46077793/how-to-save-a-custom-transformer-in-sklearn

**Comment by roy2392** [comment]
I deleted transform.py 
the one hot encoder is in: src/data/feature_engineering.py

changes are in new branch: feature/data-preprocessing.py

**Comment by YotamAflalo** [comment]
i added ``artifact_preparation.py`` and create a pkl for the transformer.

we need to train him again when we will get the original train.csv
