### ISSUE TITLE
fix beam pipeline 

### ISSUE THREAD

**Issue by roy2392** [YotamAflalo/MLOPS_mid_project#18]
replace format to dict with modular function that can take any type of order of columns 

`
'FormatToDict' >> beam.Map(lambda x: {"customerID": x[1], "tenure": x[6],
                                                 "PhoneService": x[7], "Contract": x[16], "TotalCharges": x[20]})   
`

**Comment by YotamAflalo** [comment]
steps:
1. load the csv with panda - keep just the heades
2. make a header dict/map
3. paste it in 
| 'FormatToDict' >> beam.Map(lambda x: {"customerID": x[1], "tenure": x[6],
                                                 "PhoneService": x[7], "Contract": x[16], "TotalCharges": x[20]})

**Comment by YotamAflalo** [comment]
done 

`
def get_csv_headers(file_path):

    with open(file_path, 'r') as csvfile:

        csv_reader = csv.reader(csvfile)

        headers = next(csv_reader)

    return headers
`
