### ISSUE TITLE
monitor

### ISSUE THREAD

**Issue by roy2392** [YotamAflalo/MLOPS_mid_project#7]
will be learned at 07.08.24

**Comment by YotamAflalo** [comment]
1. add whylab to the beam code
2. run whylab code on the 5 input files (as 1 per day)

### First, install the latest whylogs version
### pip install -q 'whylogs'
    
### Second, install pandas
### pip install pandas

import pandas as pd
import os
import whylogs as why

os.environ["WHYLABS_DEFAULT_ORG_ID"] = "org-QmqEak" # ORG-ID is case sensitive
os.environ["WHYLABS_API_KEY"] = "YOUR-API-KEY"
os.environ["WHYLABS_DEFAULT_DATASET_ID"] = "demo-llm-secure" # The selected project "demo-llm-secure (demo-llm-secure)" is "demo-llm-secure"

# Point to your local CSV if you have your own data
df = pd.read_csv("https://whylabs-public.s3.us-west-2.amazonaws.com/datasets/tour/current.csv")

#log dataframe
results = why.log(df)

#upload results to WhyLabs
results.writer("whylabs").write()
